name: luobo_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  app_settings: ^4.1.1
  cached_network_image: ^3.1.0
  connectivity_plus: ^2.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.1
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.3
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.0.8
  get: ^4.3.8
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.12
  webview_flutter: ^3.0.0
  package_info: ^2.0.2 

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: false
