name: luobo_project
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.15.0-226.0.dev <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.0.12
  cached_network_image: ^3.1.0

dev_dependencies:  
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
